import type { Metadata } from 'next'
import './globals.css'
import {Instrument_Serif} from "next/font/google"



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-w-[100vw] min-h-screen !overflow-x-hidden' style={{
        backgroundColor: "rgb(255,236,209)",
        background: "linear-gradient(180deg, rgba(255,236,209,1) 0%, rgba(201,255,188,1) 100%)",
      }}>{children}</body>
    </html>
  )
}
